language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git: 
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  kepp_history: true
  github_token: $GITHUB_TOKEN
  local_dir: build/
  target_branch: gh-pages
  commit_message: "Deploy del proyecto"
  on:
    branch: main